---
title: "simpleRegress"
author: "Stephanny Marthans"
date: "Spring 2021"
output:
  html_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## make a simple regression model

```{r}
bears <- read.csv(file="BEARS.csv",header = TRUE)
```
# NECK
## Model LENGTH ~ NECK  this is an example  

```{r}
simp <- lm(LENGTH~NECK,data=bears)
plot(LENGTH~NECK,data=bears)
abline(simp)
summary.lm(simp)
```

```{r}
new <- data.frame(NECK=bears$NECK [c(5, 15, 23)])
predict(simp,new,se.fit=TRUE)
```


# WEIGHT
## Model LENGTH ~ WEIGHT  

```{r}
simpHW <- lm(LENGTH~WEIGHT,data=bears)
plot(LENGTH~WEIGHT,data=bears)
abline(simpHW)
summary.lm(simpHW)
```

```{r}
new <- data.frame(WEIGHT=bears$WEIGHT [c(5, 15, 23)])
predict(simpHW,new,se.fit=TRUE)
```

# HEADLEN
## Model LENGTH ~ HEADLEN
```{r}
simpHW <- lm(LENGTH~HEADLEN,data=bears)
plot(LENGTH~HEADLEN,data=bears)
abline(simpHW)
summary.lm(simpHW)
```

```{r}
new <- data.frame(HEADLEN=bears$HEADLEN [c(5, 15, 23)])
predict(simpHW,new,se.fit=TRUE)
```



## Surely there is another variable that can better predict LENGTH than NECK. Find one and compare its performance to that of neck by it value of Adjusted-Rsquared (bigger is better).

